# Generated by Django 5.0a1 on 2023-10-24 03:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pro13exapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jikwon",
            options={},
        ),
    ]
