# Generated by Django 5.0a1 on 2023-10-24 03:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pro13exapp", "0003_alter_jikwon_buser_num_alter_jikwon_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jikwon",
            options={"managed": False},
        ),
    ]
