# Generated by Django 5.0a1 on 2023-10-24 03:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pro13exapp", "0004_alter_jikwon_options"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="jikwon",
            table="jikwon",
        ),
    ]
